plugins {
    id 'java'
    id 'org.springframework.boot' version '4.1.1'
}

group = 'hu.motorworkshop'
version = '0.0.1-SNAPSHOT'
description = 'Motor workshop API'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation platform(org.springframework.boot.gradle.plugin.SpringBootPlugin.BOM_COORDINATES)

    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'net.coobird:thumbnailator:0.4.21'
    implementation 'com.twelvemonkeys.imageio:imageio-webp:3.14.0'

    runtimeOnly 'org.xerial:sqlite-jdbc:3.50.3.0'
    implementation 'org.hibernate.orm:hibernate-community-dialects'

    implementation 'io.github.openhtmltopdf:openhtmltopdf-pdfbox:1.1.75'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
    useJUnitPlatform()
}