spring:
  application:
    name: motor-workshop-api

  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB

  datasource:
    url: jdbc:sqlite:./data/motoros.db

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.SQLiteDialect
        jdbc:
          time_zone: UTC

server:
  port: ${SERVER_PORT:8081}

app:
  storage:
    work-order-photos: ${PHOTO_STORAGE_PATH:./data/work-order-photos}